### PR TITLE
Feature/stereoscopic mode

### PR DESCRIPTION
**Pull request by nategreco**
- Corrected wrong return value from camera selection (#26)

- Added setStereoMode() method to raspicam/raspicam_cv/raspicam_still/raspicam_still_cv classess

### CODE REVIEW

**Comment by nategreco** [comment]
See in practice - https://github.com/nategreco/StereoVisionTest

**Comment by cedricve** [comment]
@nategreco we got some conflicts, after merging your previous PR.

**Comment by nategreco** [comment]
Ok, ill take a look at it in the next hour or so.  Maybe i should have
waited for pull request #26 to be merged and branched from develop again?

**Comment by cedricve** [comment]
cool @nategreco

**Comment by nategreco** [comment]
Ok, there was something it didn't like about the formatting with the setStereoMode() declaration in private_still_impl.h.  Thanks for merging!

**Pull request merged**
